/* 用户旅程状态回归：偏好、明确限制、确认解析、日期与草案恢复。 */
import assert from 'node:assert/strict';
import guide from '../mixtouring-hifi/assets/trip-guide.js';
import { parseGuideTurn } from './lib/guide.mjs';
import { buildTravelIntent, planAnywhere } from './lib/anywhere.mjs';
import { registerJourneyPlan, guidePlanFromId } from './lib/journey.mjs';
const now = Date.parse('2026-09-27T04:00:00Z');
const direct = { id: 'direct', kind: 'direct', legs: [{ from: '北京', to: '阿拉木图', mode_guess: 'plane' }] };
const road = { id: 'road', kind: 'discovered', legs: [{ from: '北京', to: '伊宁', mode_guess: null }, { from: '伊宁', to: '阿拉木图', mode_guess: 'road', via: '霍尔果斯' }] };
const rail = { id: 'rail', kind: 'mixed', legs: [{ from: '北京', to: '乌鲁木齐', mode_guess: 'rail' }, { from: '乌鲁木齐', to: '阿拉木图', mode_guess: 'plane' }] };
const candidates = [direct, road, rail];
assert.equal(guide.question({}, candidates).key, 'pace');
assert.equal(guide.question({ pace: 'explore' }, candidates).key, 'nights');
assert.equal(guide.question({ pace: 'explore', nights: 2 }, candidates).key, 'road');
assert.equal(guide.question({ pace: 'explore', nights: 2, skipped: ['road'] }, candidates), null);
assert.equal(guide.question({ pace: 'explore', nights: 2 }, [direct, rail]), null);
assert.ok(guide.question({}, candidates).title.includes('伊宁'));
assert.equal(guide.question({ skipped: ['pace'] }, candidates), null);
assert.equal(guide.rank(candidates, { pace: 'explore' }).items[0].candidate.id, 'road');
assert.equal(guide.rank(candidates, { pace: 'simple' }).items[0].candidate.id, 'direct');
const soft = guide.rank(candidates, { pace: 'explore', road: 'prefer_other' });
assert.equal(soft.items.length, 3);
assert.equal(soft.items[0].candidate.id, 'rail');
const hard = guide.rank(candidates, { road: 'exclude' });
assert.equal(hard.omitted, 1);
assert.equal(hard.items.length, 2);
assert.deepEqual(guide.rank(candidates, {}).items.map((x) => x.candidate.id), ['direct', 'road', 'rail']);
assert.equal(guide.rank([road], { road: 'exclude' }).items.length, 0);
assert.deepEqual(guide.parse('可以停两晚，但不想一直坐长途车').patch, { pace: 'explore', road: 'prefer_other', nights: 2 });
assert.equal(guide.parse('不坐大巴').patch.road, 'exclude');
assert.equal(guide.parse('可以坐大巴').patch.road, 'open');
assert.equal(guide.parse('停两天').patch.nights, undefined);
assert.equal(parseGuideTurn('想吃好吃的', now).recognized, false);
assert.equal(parseGuideTurn('预算3000元，最多换一次', now).constraints.max_transfers, 1);
assert.equal(parseGuideTurn('取消预算限制', now).constraints.budget_max_cny, null);
const returnOnly = parseGuideTurn('返回时间改到10月8号', now).travel;
assert.equal(returnOnly.return_window, '2026-10-08 ~ 2026-10-08');
assert.equal(returnOnly.outbound_window, undefined);
const unsureStay = parseGuideTurn('不想停两晚了', now);
assert.equal(unsureStay.recognized, false);
assert.ok(unsureStay.message.includes('取消中途停留'));
assert.equal(parseGuideTurn('取消中途停留', now).preferences.nights, 0);
assert.equal(parseGuideTurn('改成一晚', now).preferences.nights, 1);
assert.ok(parseGuideTurn('只看直达', now).notes[0].includes('仍保留其他走法'));
const bothDates = parseGuideTurn('返程10月8号，去程9月30号', now).travel;
assert.equal(bothDates.outbound_window, '2026-09-30 ~ 2026-09-30');
assert.equal(bothDates.return_window, '2026-10-08 ~ 2026-10-08');
assert.equal(parseGuideTurn('取消返程', now).travel.return_window, null);
assert.equal(parseGuideTurn('最晚10月3号到', now).recognized, false);
assert.equal(parseGuideTurn('夜间到达不要', now).constraints.night_arrival, 'avoid');
assert.equal(parseGuideTurn('预算改到4000元', now).constraints.budget_max_cny, 4000);
/* 卡 B：不开车与住宿约束的对话确认与撤销 */
assert.equal(parseGuideTurn('我不会开车', now).constraints.no_self_drive, true);
assert.ok(parseGuideTurn('我不会开车', now).labels.some((l) => l.includes('不开车')));
assert.equal(parseGuideTurn('可以自己开车了', now).constraints.no_self_drive, null);
const stayTurn = parseGuideTurn('9月30日住伊宁', now);
assert.equal(stayTurn.constraints.lodging_stays.length, 1);
assert.equal(stayTurn.constraints.lodging_stays[0].city, '伊宁');
assert.ok(stayTurn.labels.some((l) => l.includes('住 伊宁')));
assert.equal(parseGuideTurn('不住了，取消住宿', now).constraints.lodging_stays, null);
assert.equal(parseGuideTurn('改成单程', now).travel.trip_type, 'one_way');
const arrival = parseGuideTurn('国庆1-3号之间到', now).travel.arrival_window;
assert.equal(arrival, '2026-10-01 ~ 2026-10-03');
assert.equal(buildTravelIntent('停两晚', { arrival_window: arrival }, now).intent.arrival_window, arrival);
assert.equal(buildTravelIntent('', { trip_type: 'one_way', return_window: '2026-10-07 ~ 2026-10-07' }, now).intent.return_window, null);
assert.notEqual(guide.routeKey(road), guide.routeKey({ ...road, legs: road.legs.map((x) => ({ ...x, via: '巴克图' })) }));
const saved = JSON.parse(JSON.stringify({ preferences: { pace: 'explore', nights: 2 }, travel: { arrival_window: arrival }, candidate_key: guide.routeKey(road) }));
assert.equal(guide.clean(saved.preferences).nights, 2);
assert.equal(saved.candidate_key, guide.routeKey(road));
const plan = await planAnywhere({ origin: '北京', destination: '喀什', constraints: { max_transfers: null } }, { callJson: async () => null, env: {} });
assert.equal(plan.intent.constraints.max_transfers, undefined);
assert.ok(plan.candidates.some((x) => x.kind !== 'direct'));
const guidePlan = { intent: { origin: '北京', destination: '阿拉木图' }, candidates: [direct, {
  ...road, explanation: '搜索资料提示可经伊宁方向探索；班期待查',
  basis: { sources: [{ title: '国际道路客运班线经营许可', link: 'https://example.org/source' }] }
}] };
const planId = registerJourneyPlan(guidePlan, now);
assert.equal(guidePlanFromId(planId, now), guidePlan);
assert.equal(guidePlanFromId('invalid', now), null);
assert.ok(parseGuideTurn('为什么推荐伊宁？', now, guidePlan).message.includes('国际道路客运班线经营许可'));
assert.ok(parseGuideTurn('有班次和票价吗？', now, guidePlan).message.includes('尚无'));
assert.ok(parseGuideTurn('那直达呢？', now, guidePlan).message.includes('待核验'));
console.log('✓ 对话引导：选择重排、软硬偏好、跳过、撤销基线、补充确认、到达日期、停留与草案结构回归通过');
